'use client'
import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import { api, InvestigationDetail, TaggedTransaction, StepLogEntry } from '@/lib/api'
import MoneyFlowGraph from '@/components/MoneyFlowGraph'
import CrossClientNetwork from '@/components/CrossClientNetwork'
import STRReview from '@/components/STRReview'

const STATUS_COLORS: Record<string, string> = {
  open: 'bg-blue-100 text-blue-700',
  running: 'bg-indigo-100 text-indigo-700',
  de_escalated: 'bg-green-100 text-green-700',
  fast_tracked: 'bg-amber-100 text-amber-700',
  str_drafted: 'bg-orange-100 text-orange-700',
  filed: 'bg-purple-100 text-purple-700',
  dismissed: 'bg-slate-100 text-slate-500',
}

const INDICATOR_CHIP: Record<string, string> = {
  structuring: 'bg-red-100 text-red-700',
  layering: 'bg-orange-100 text-orange-700',
  rapid_crypto_conversion: 'bg-amber-100 text-amber-700',
  income_inconsistency: 'bg-yellow-100 text-yellow-800',
  new_counterparty_burst: 'bg-purple-100 text-purple-700',
  default: 'bg-slate-100 text-slate-700',
}

const LAYER_BADGE: Record<number, string> = {
  1: 'bg-indigo-100 text-indigo-700',
  2: 'bg-amber-100 text-amber-700',
  3: 'bg-orange-100 text-orange-700',
}
const LAYER_LABELS: Record<number, string> = {
  1: 'L1 Behavioral',
  2: 'L2 Response',
  3: 'L3 Orchestrator',
}

const ACTION_ICON: Record<string, string> = {
  notification_sent: '🔔',
  step_up_auth: '🔒',
  follow_up_call_scheduled: '📞',
  info_request_sent: '📋',
  auto_de_escalated: '✅',
  guardrail_intercept: '⚡',
  coordinated_alert: '🔗',
}

type Tab = 'evidence' | 'fintrac' | 'steps' | 'audit'

function TransactionRow({ txn }: { txn: TaggedTransaction }) {
  const indicators = txn.fintrac_indicators || []
  return (
    <tr className="border-b border-slate-100">
      <td className="px-3 py-2 text-xs font-mono text-slate-500 whitespace-nowrap">
        {new Date(txn.timestamp).toLocaleDateString()}
      </td>
      <td className="px-3 py-2 text-xs text-slate-600">{txn.type.replace(/_/g, ' ')}</td>
      <td className="px-3 py-2 text-xs text-slate-500">{txn.product}</td>
      <td className="px-3 py-2 text-xs font-semibold text-slate-800">
        ${txn.amount.toLocaleString()}
      </td>
      <td className="px-3 py-2 text-xs text-slate-500">{txn.counterparty_name || '—'}</td>
      <td className="px-3 py-2">
        <div className="flex flex-wrap gap-1">
          {indicators.map((ind, i) => (
            <span
              key={i}
              className={`text-xs px-1.5 py-0.5 rounded-full font-medium ${INDICATOR_CHIP[ind.indicator] || INDICATOR_CHIP.default}`}
              title={ind.reasoning}
            >
              {ind.indicator.replace(/_/g, ' ')} {(ind.confidence * 100).toFixed(0)}%
            </span>
          ))}
          {indicators.length === 0 && <span className="text-slate-300">—</span>}
        </div>
      </td>
    </tr>
  )
}

function FINTRACDocument({ inv }: { inv: InvestigationDetail }) {
  const draft = inv.str_draft
  const [deciding, setDeciding] = useState(false)
  const [decided, setDecided] = useState(false)

  const handleDecision = async (decision: 'approve' | 'dismiss') => {
    setDeciding(true)
    try {
      await api.decideSTR(inv.id, decision, '')
      setDecided(true)
      window.location.reload()
    } catch {
      setDeciding(false)
    }
  }

  if (!draft) {
    return (
      <div className="p-8 text-center text-slate-400 text-sm">
        {inv.status === 'de_escalated'
          ? 'Investigation was de-escalated. No STR draft generated.'
          : 'No FINTRAC document available yet.'}
      </div>
    )
  }

  return (
    <div
      className="font-mono text-sm rounded-xl overflow-hidden"
      style={{ background: '#0d1117', border: '1px solid rgba(255,255,255,0.08)' }}
    >
      {/* Document header */}
      <div
        className="px-6 py-4"
        style={{ borderBottom: '1px solid rgba(255,255,255,0.08)', background: 'rgba(99,102,241,0.06)' }}
      >
        <div className="text-xs text-indigo-400 tracking-widest mb-1">PROCEEDS OF CRIME (MONEY LAUNDERING) AND TERRORIST FINANCING ACT, S. 7</div>
        <div className="text-base font-bold text-slate-100 tracking-wide">
          SUSPICIOUS TRANSACTION REPORT — {draft.status === 'approved' ? 'FILED' : draft.status === 'dismissed' ? 'DISMISSED' : 'DRAFT'}
        </div>
        <div className="text-xs text-slate-500 mt-1">
          Subject: {inv.client_name} &nbsp;|&nbsp; Investigation: {inv.id.slice(0, 8).toUpperCase()} &nbsp;|&nbsp; Generated by AI · Requires human approval
        </div>
      </div>

      <div className="p-6 space-y-5">
        {/* Subject profile */}
        {draft.subject_profile && (
          <Section title="1. SUBJECT PROFILE" color="text-indigo-400">
            <p className="text-slate-300 leading-relaxed whitespace-pre-wrap">{draft.subject_profile}</p>
          </Section>
        )}

        {/* Activity description */}
        {draft.activity_description && (
          <Section title="2. ACTIVITY DESCRIPTION" color="text-indigo-400">
            <p className="text-slate-300 leading-relaxed whitespace-pre-wrap">{draft.activity_description}</p>
          </Section>
        )}

        {/* FINTRAC indicators */}
        {draft.indicators_present?.length > 0 && (
          <Section title="3. FINTRAC INDICATORS" color="text-indigo-400">
            <div className="space-y-2">
              {draft.indicators_present.map((ind, i) => (
                <div key={i} className="border-l-2 border-red-700/50 pl-3 py-1">
                  <div className="flex items-center justify-between flex-wrap gap-2">
                    <span className="text-red-400 font-bold text-xs uppercase tracking-wider">
                      {ind.indicator.replace(/_/g, ' ')}
                    </span>
                    <div className="flex items-center gap-2">
                      <span className="text-xs text-slate-500">confidence: {((ind.confidence ?? 0) * 100).toFixed(0)}%</span>
                      {ind.fintrac_ref && (
                        <span className="text-xs text-slate-600 bg-slate-800 px-1.5 py-0.5 rounded">
                          {ind.fintrac_ref}
                        </span>
                      )}
                    </div>
                  </div>
                  {ind.reasoning && (
                    <p className="text-xs text-slate-400 mt-1 leading-relaxed">{ind.reasoning}</p>
                  )}
                </div>
              ))}
            </div>
          </Section>
        )}

        {/* Behavioral context */}
        {draft.behavioral_context && (
          <Section title="4. BEHAVIORAL CONTEXT" color="text-indigo-400">
            <p className="text-slate-300 leading-relaxed whitespace-pre-wrap">{draft.behavioral_context}</p>
          </Section>
        )}

        {/* Network analysis */}
        {draft.network_analysis && (
          <Section title="5. NETWORK ANALYSIS" color="text-indigo-400">
            <p className="text-slate-300 leading-relaxed whitespace-pre-wrap">{draft.network_analysis}</p>
          </Section>
        )}

        {/* Full narrative */}
        {draft.narrative_full && (
          <Section title="6. FULL NARRATIVE" color="text-indigo-400">
            <div
              className="text-xs text-slate-400 leading-relaxed whitespace-pre-wrap overflow-y-auto"
              style={{ maxHeight: 320 }}
            >
              {draft.narrative_full}
            </div>
          </Section>
        )}

        {/* Key uncertainties */}
        {draft.key_uncertainties?.length > 0 && (
          <Section title="KEY UNCERTAINTIES" color="text-amber-400">
            <ul className="space-y-1">
              {draft.key_uncertainties.map((u, i) => (
                <li key={i} className="flex gap-2 text-xs text-slate-400">
                  <span className="text-amber-600 shrink-0">•</span>
                  <span>{u}</span>
                </li>
              ))}
            </ul>
          </Section>
        )}

        {/* Recommendation */}
        {draft.recommendation && (
          <Section title="RECOMMENDATION" color="text-emerald-400">
            <p className="text-emerald-300 font-semibold">{draft.recommendation}</p>
          </Section>
        )}

        {/* Pending human review tag */}
        {draft.status === 'draft' && (
          <div
            className="text-center text-xs tracking-widest py-2 rounded"
            style={{ color: '#f97316', border: '1px dashed rgba(249,115,22,0.3)' }}
          >
            [PENDING HUMAN REVIEW AND APPROVAL]
          </div>
        )}
      </div>

      {/* Human decision footer */}
      {draft.status === 'draft' && (
        <div
          className="px-6 py-4 flex items-center justify-between gap-4 flex-wrap"
          style={{ borderTop: '1px solid rgba(255,255,255,0.06)', background: 'rgba(0,0,0,0.3)' }}
        >
          <div className="text-xs text-slate-500">
            Layer 4 — Human Decision · Under PCMLTFA, the analyst signs this personally
          </div>
          <div className="flex gap-3">
            <button
              onClick={() => handleDecision('dismiss')}
              disabled={deciding || decided}
              className="text-xs px-4 py-2 rounded border border-slate-700 text-slate-400 hover:border-slate-500 hover:text-slate-200 transition-colors disabled:opacity-40"
            >
              Dismiss
            </button>
            <button
              onClick={() => handleDecision('approve')}
              disabled={deciding || decided}
              className="text-xs px-4 py-2 rounded font-semibold transition-colors disabled:opacity-40"
              style={{ background: '#4f46e5', color: 'white' }}
            >
              Approve & File STR
            </button>
          </div>
        </div>
      )}

      {(draft.status === 'approved' || draft.status === 'dismissed') && (
        <div
          className="px-6 py-3 text-xs text-center"
          style={{
            borderTop: '1px solid rgba(255,255,255,0.06)',
            color: draft.status === 'approved' ? '#22c55e' : '#94a3b8',
          }}
        >
          {draft.status === 'approved'
            ? `Filed by ${draft.decided_by ?? 'analyst'} on ${draft.decided_at ? new Date(draft.decided_at).toLocaleDateString() : '—'}`
            : `Dismissed by ${draft.decided_by ?? 'analyst'}`}
          {draft.analyst_notes && <span className="ml-2 text-slate-500">— {draft.analyst_notes}</span>}
        </div>
      )}
    </div>
  )
}

function Section({ title, color, children }: { title: string; color: string; children: React.ReactNode }) {
  return (
    <div>
      <div className={`text-xs font-bold tracking-widest mb-2 ${color}`}>{title}</div>
      {children}
    </div>
  )
}

function AgentStepsTab({ stepLog }: { stepLog: StepLogEntry[] }) {
  if (!stepLog || stepLog.length === 0) {
    return (
      <div className="py-10 text-center text-sm text-slate-400">
        No agent steps recorded. Run the simulate pipeline from the Dashboard.
      </div>
    )
  }

  return (
    <div className="space-y-3">
      <p className="text-xs text-slate-400">
        {stepLog.length} pipeline steps · Layer 1 (Behavioral) → Layer 2 (Response) → Layer 3 (Orchestrator)
      </p>
      <div className="relative">
        <div className="absolute left-3 top-0 bottom-0 w-px bg-slate-200" />
        <div className="space-y-3 pl-8">
          {stepLog.map((step, i) => (
            <div key={i} className="relative">
              <div className="absolute -left-5 top-1 w-2.5 h-2.5 rounded-full bg-emerald-400 border-2 border-white" />
              <div className="bg-white rounded-lg border border-slate-100 p-3 shadow-sm">
                <div className="flex items-center gap-2 flex-wrap mb-1">
                  <span className={`text-xs font-semibold px-1.5 py-0.5 rounded ${LAYER_BADGE[step.layer] || 'bg-slate-100 text-slate-600'}`}>
                    {LAYER_LABELS[step.layer] || `Layer ${step.layer}`}
                  </span>
                  {step.action_type && (
                    <span className="text-xs">{ACTION_ICON[step.action_type] || ''}</span>
                  )}
                  <span className="text-xs font-medium text-slate-700">{step.label}</span>
                  <span className="ml-auto text-xs text-slate-400 font-mono">
                    {new Date(step.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}
                  </span>
                </div>
                {step.details && (
                  <p className="text-xs text-slate-500 leading-relaxed">{step.details}</p>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

export default function InvestigationDetailPage() {
  const params = useParams()
  const [inv, setInv] = useState<InvestigationDetail | null>(null)
  const [auditLog, setAuditLog] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [tab, setTab] = useState<Tab>('fintrac')

  const load = async () => {
    try {
      const data = await api.getInvestigation(params.id as string)
      setInv(data)
      // Fetch audit in background
      ;(api as any).getAuditTrail?.(params.id as string)
        ?.then((a: any[]) => setAuditLog(a))
        ?.catch(() => {})
    } catch {
      setError('Investigation not found')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { load() }, [params.id])

  // Also fetch audit via the documented endpoint
  useEffect(() => {
    if (!params.id) return
    fetch(`${process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000'}/investigations/${params.id}/audit`)
      .then(r => r.ok ? r.json() : [])
      .then(setAuditLog)
      .catch(() => {})
  }, [params.id])

  if (loading) return <div className="py-20 text-center text-slate-400">Loading…</div>
  if (error || !inv) return <div className="py-20 text-center text-slate-400">{error}</div>

  const taggedTxns: TaggedTransaction[] = inv.str_draft?.tagged_transactions || []

  const tabs: { id: Tab; label: string }[] = [
    { id: 'fintrac', label: 'FINTRAC Document' },
    { id: 'evidence', label: 'Evidence' },
    { id: 'steps', label: `Agent Steps ${inv.step_log?.length ? `(${inv.step_log.length})` : ''}` },
    { id: 'audit', label: 'Audit' },
  ]

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-start justify-between flex-wrap gap-4">
        <div>
          <div className="flex items-center gap-3">
            <h1 className="text-2xl font-bold text-slate-900">
              <Link href={`/clients/${inv.client_id}`} className="hover:underline text-indigo-700">
                {inv.client_name}
              </Link>
            </h1>
            <span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${STATUS_COLORS[inv.status] || ''}`}>
              {inv.status.replace(/_/g, ' ')}
            </span>
          </div>
          <p className="text-xs text-slate-400 font-mono mt-1">{inv.id}</p>
        </div>
        <div className="flex flex-col items-end gap-1">
          {inv.classification && (
            <div className="text-sm font-semibold text-slate-700">
              {inv.classification.replace(/_/g, ' ')}
              {inv.confidence !== null && (
                <span className="text-slate-400 font-normal ml-1">({inv.confidence?.toFixed(0)}% confidence)</span>
              )}
            </div>
          )}
          {inv.is_coordinated && (
            <span className="text-xs font-semibold text-red-600 bg-red-50 px-2 py-0.5 rounded-full">
              Coordinated — {inv.correlated_client_ids.length + 1} linked clients
            </span>
          )}
        </div>
      </div>

      {/* Tab bar */}
      <div className="flex gap-1 border-b border-slate-200">
        {tabs.map(({ id, label }) => (
          <button
            key={id}
            onClick={() => setTab(id)}
            className={`px-4 py-2.5 text-sm font-medium border-b-2 transition-colors whitespace-nowrap ${
              tab === id
                ? 'border-indigo-600 text-indigo-700'
                : 'border-transparent text-slate-500 hover:text-slate-700'
            }`}
          >
            {label}
          </button>
        ))}
      </div>

      {/* ── FINTRAC Document tab ── */}
      {tab === 'fintrac' && <FINTRACDocument inv={inv} />}

      {/* ── Evidence tab ── */}
      {tab === 'evidence' && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
            {inv.str_draft?.money_flow?.nodes?.length ? (
              <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-5">
                <h2 className="text-sm font-semibold text-slate-700 mb-3">Money Flow</h2>
                <MoneyFlowGraph data={inv.str_draft.money_flow} />
              </div>
            ) : null}
            {inv.is_coordinated && inv.network_graph?.nodes?.length ? (
              <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-5">
                <h2 className="text-sm font-semibold text-slate-700 mb-1">Cross-Client Network</h2>
                <p className="text-xs text-slate-400 mb-3">
                  Clients share wallet cluster or temporal deposit pattern
                </p>
                <CrossClientNetwork data={inv.network_graph} />
              </div>
            ) : null}
          </div>

          {taggedTxns.length > 0 && (
            <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
              <div className="px-5 py-3 border-b border-slate-200">
                <h2 className="text-sm font-semibold text-slate-700">Transaction Timeline — FINTRAC Tagged</h2>
              </div>
              <div className="overflow-x-auto max-h-72 overflow-y-auto">
                <table className="w-full">
                  <thead className="bg-slate-50 sticky top-0">
                    <tr>
                      {['Date', 'Type', 'Product', 'Amount', 'Counterparty', 'Indicators'].map((h) => (
                        <th key={h} className="text-left px-3 py-2 text-xs font-semibold text-slate-500">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {taggedTxns.map((t) => <TransactionRow key={t.id} txn={t} />)}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {inv.reasoning && (
            <div className="bg-slate-50 rounded-xl border border-slate-200 p-5">
              <h2 className="text-sm font-semibold text-slate-700 mb-2">AI Classification Reasoning</h2>
              <p className="text-sm text-slate-600 leading-relaxed">{inv.reasoning}</p>
            </div>
          )}
        </div>
      )}

      {/* ── Agent Steps tab ── */}
      {tab === 'steps' && (
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6">
          <h2 className="text-sm font-semibold text-slate-700 mb-4">Agent Research Pipeline</h2>
          <AgentStepsTab stepLog={inv.step_log || []} />
        </div>
      )}

      {/* ── Audit tab ── */}
      {tab === 'audit' && (
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="px-5 py-3 border-b border-slate-200">
            <h2 className="text-sm font-semibold text-slate-700">Audit Trail</h2>
          </div>
          <div className="divide-y divide-slate-50 max-h-96 overflow-y-auto">
            {auditLog.length === 0 && (
              <p className="px-5 py-4 text-sm text-slate-400">No audit entries.</p>
            )}
            {auditLog.map((entry: any) => (
              <div key={entry.id} className="flex items-start gap-3 px-5 py-2.5 text-sm">
                <span className="text-xs text-slate-400 font-mono whitespace-nowrap pt-0.5">
                  {new Date(entry.timestamp).toLocaleString()}
                </span>
                <span className="text-slate-700 flex-1">{entry.action.replace(/_/g, ' ')}</span>
                <span className="text-xs text-slate-400 shrink-0">{entry.actor}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
